[tasks.serve]
description = "devel only"
run = """
  mdbook serve
"""

[tasks.build]
description = "pre commit build"
run = """
  mdbook build
"""

[tasks.openurl]
description = "https://dirtslayer.github.io/blog/"
shell = "bash -c"
run = """
  xdg-open https://dirtslayer.github.io/blog/ & disown
"""


